#include "chain_button.h"

#ifdef __cplusplus
extern "C" {
#endif

#define WIDGET_TYPE_CHAIN_BUTTON (ChainButtonGetType())
#define WIDGET_CHAIN_BUTTON(OBJ) (G_TYPE_CHECK_INSTANCE_CAST((OBJ), WIDGET_TYPE_CHAIN_BUTTON, CHAIN_BUTTON)
#define WIDGET_CHAIN_BUTTON_CLASS(CLASS) (G_TYPE_CHECK_CLASS_CAST((CLASS), CHAIN_BUTTON_CLASS)
#define WIDGET_IS_CHAIN_BUTTON(CLASS) (G_TYPE_CHECK_INSTANCE_TYPE((CLASS, WIDGET_TYPE_CHAIN_BUTTON))

#ifdef __cplusplus
}
#endif
