#ifndef _INCLUDED_CONFIGURE_H_
#define _INCLUDED_CONFIGURE_H_

#define APPLICATION_BUFFER_SIZE 32

#define CHECK_MEMORY_POOL 0

#define WHITE_TEXTURE_SIZE 128

#define DEFAULT_ASPECT_RATIO (16.0f/9.0f)

#endif	// #ifndef _INCLUDED_CONFIGURE_H_
