#ifndef _INCLUDED_EFFECT_H_
#define _INCLUDED_EFFECT_H_

typedef enum _eEFFECT_SCRIPT_ORDER_TYPE
{
	EFFECT_SCRIPT_ORDER_TYPE_PRE_PROCESS,
	EFFECT_SCRIPT_ORDER_TYPE_STANDARD,
	EFFECT_SCRIPT_ORDER_TYPE_STANDARD_OFFSCRESSN,
	EFFECT_SCRIPT_ORDER_TYPE_POST_PROCESS,
	EFFECT_SCRIPT_ORDER_TYPE_AUTO_DETECTION,
	EFFECT_SCRIPT_ORDER_TYPE_DEFAULT,
	MAX_EFFECT_SCRIPT_ORDER_TYPE
} eEFFECT_SCRIPT_ORDER_TYPE;

typedef struct _EFFECT_INETERFACE
{
	eEFFECT_SCRIPT_ORDER_TYPE order_type;
} EFFECT_INTERFACE;

#endif	// #ifndef _INCLUDED_EFFECT_H_
